/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/onboarding-hero`; params?: Router.UnknownInputParams; } | { pathname: `/home-preview`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-step1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-children`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/paywall` | `/paywall`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/OnboardingContext`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/onboarding-hero`; params?: Router.UnknownOutputParams; } | { pathname: `/home-preview`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding-step1`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding-children`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/paywall` | `/paywall`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/tasks` | `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/contexts/OnboardingContext`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/onboarding-hero${`?${string}` | `#${string}` | ''}` | `/home-preview${`?${string}` | `#${string}` | ''}` | `/onboarding-step1${`?${string}` | `#${string}` | ''}` | `/onboarding-children${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/paywall${`?${string}` | `#${string}` | ''}` | `/paywall${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}/tasks${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/contexts/OnboardingContext${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/onboarding-hero`; params?: Router.UnknownInputParams; } | { pathname: `/home-preview`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-step1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-children`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/paywall` | `/paywall`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/OnboardingContext`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
